CPP=g++
CPP_FLAGS=-I/usr/local/Cellar/eigen/3.3.9/include/eigen3 -I/usr/local/include
LD_FLAGS=-L/usr/local/lib -lqqwing

all: sudoku

sudoku: sudoku.o
	${CPP} -o sudoku sudoku.o ${LD_FLAGS}

sudoku.o: sudoku.cpp
	${CPP} ${CPP_FLAGS} -c sudoku.cpp -o sudoku.o

clean:
	-rm sudoku sudoku.o
